version: "3.9"
services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env
    ports:
      - 5433:5432
    restart: always
  redis:
    image: redis:7.0.4-alpine
    volumes:
      - redis:/data
    ports:
      - 6380:6379
    restart: always
  api:
    build: .
    command: foreman start -f Procfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/d-api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DB_NAME}_development
      REDIS_URL: ${REDIS_HOST}://${REDIS_HOST}:${REDIS_PORT}
    restart: always
volumes:
  pgdata:
  redis:
